server:
  port: 8080

spring:
  application:
    name: visa-client

# Visa server connection
visa:
  base-url: "https://localhost:8443"
  auth:
    user-id: "1WM2TT4IHPXC8DQ5I3CH21n1rEBGK-Eyv_oLdzE2VZpDqRn_U"
    password: "19JRVdej9"

# mTLS Configuration
ssl:
  key-store: C:/Users/Vignesh/visa-projects/certs/client-keystore.p12
  key-store-password: changeit
  key-store-type: PKCS12
  trust-store: C:/Users/Vignesh/visa-projects/certs/client-truststore.p12
  trust-store-password: changeit
  trust-store-type: PKCS12

# MLE Configuration
mle:
  key-id: "7f591161-6b5f-4136-80b8-2ae8a44ad9eb"
  # Server's public cert - used to ENCRYPT outgoing requests to server
  server-public-cert-path: C:/Users/Vignesh/visa-projects/certs/mle-server-public.pem
  # Client's private key - used to DECRYPT incoming responses from server
  client-private-key-path: C:/Users/Vignesh/visa-projects/certs/mle-client-private.pem

logging:
  level:
    com.visa.client: DEBUG
